version: "3.7"
services:
  imageservice:
    build: ./
    user: "${UID}:${GID}"
    ports:
      - "8756:8000"
    expose:
      - "8756"
    volumes:
      - ./:/var/www/html/image
    command: /bin/sh /var/www/html/image/start.sh
